# Generated by Django 5.2.8 on 2025-11-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
