# Generated by Django 5.2.8 on 2025-12-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', '-created'], 'verbose_name': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
