# Generated by Django 5.2.8 on 2025-12-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_message_options_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Получать уведомления на почту'),
        ),
    ]
