# Generated by Django 6.0.1 on 2026-01-21 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_board_members'),
        ('users', '0008_profile_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='invitation_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='related_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.board', verbose_name='Приглашение в доску'),
        ),
    ]
