# Generated by Django 6.0.1 on 2026-01-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_message_invitation_status_message_related_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='invitation_status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='related_board',
        ),
    ]
