# Generated by Django 5.2.8 on 2025-12-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('member', 'member'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
    ]
