# Generated by Django 6.0.1 on 2026-02-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('column', 'position')},
        ),
    ]
