# Generated by Django 6.0.1 on 2026-02-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_add_task_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
