# Generated by Django 5.2.8 on 2026-01-07 07:37

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_alter_taskfile_file_alter_taskfile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(upload_to=boards.models.task_file_path),
        ),
    ]
