# Generated by Django 5.2.8 on 2026-01-09 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_alter_boardpermit_board_alter_boardpermit_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('average', 'average'), ('high', 'high'), ('maximal', 'maximal')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='boardpermit',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board'),
        ),
        migrations.AlterField(
            model_name='boardpermit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
