# Generated by Django 5.2.8 on 2026-01-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_board_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
