# Generated by Django 5.2.8 on 2026-02-03 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_board_is_archived_task_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.ManyToManyField(blank=True, related_name='responsible_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
