# Generated by Django 6.0.1 on 2026-02-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_board_position_userboardorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
