# Generated by Django 5.2.8 on 2026-02-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_alter_task_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userboardorder',
            options={'ordering': ['position_board']},
        ),
        migrations.RemoveField(
            model_name='userboardorder',
            name='position',
        ),
        migrations.AddField(
            model_name='userboardorder',
            name='position_board',
            field=models.IntegerField(default=0),
        ),
    ]
