# Generated by Django 5.2.8 on 2026-02-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_alter_userboardorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userboardorder',
            options={'ordering': ['position']},
        ),
        migrations.RenameField(
            model_name='userboardorder',
            old_name='position_board',
            new_name='position',
        ),
    ]
